// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

var cache = /* array */[
  "",
  " ",
  "  ",
  "   ",
  "    ",
  "     ",
  "      ",
  "       ",
  "        ",
  "         "
];

function leftPad(str, len, character) {
  var nLen = len - str.length | 0;
  var nChar = character.length ? character : " ";
  var match = nChar;
  var match$1 = +(nLen < 10);
  var exit = 0;
  if (match === " ") {
    if (match$1 !== 0) {
      return Caml_array.caml_array_get(cache, nLen) + str;
    } else {
      exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    var pad = "";
    var $$break = /* false */0;
    while(!$$break) {
      var match$2 = nLen & 1;
      var match$3 = nLen;
      if (match$2 !== 1) {
        if (match$3 !== 0) {
          nLen = (nLen >>> 1);
          nChar = nChar + nChar;
        } else {
          $$break = /* true */1;
        }
      } else if (match$3 !== 0) {
        pad = pad + nChar;
        nLen = (nLen >>> 1);
        nChar = nChar + nChar;
      } else {
        pad = pad + nChar;
        $$break = /* true */1;
      }
    };
    return pad + str;
  }
  
}

exports.cache   = cache;
exports.leftPad = leftPad;
/* No side effect */
